base_url = "https://getzola.github.io/after-dark/"
compile_sass = true
# title = "after-dark theme"
# description = "A robust, elegant dark theme"
generate_feeds = true

[markdown]
[markdown.highlighting]
theme = "dark-plus"

[extra]
author = "Author Name"
after_dark_menu = [{ url = "$BASE_URL", name = "Home" }]
google_analytics = ""

[extra.telegram_channel]
created_at = ""
id = ""
logo = "logo.jpg"
